version: "3.7"

services:
  backend:
    image: <your aws account>.dkr.ecr.<your aws region>.amazonaws.com/docker-ecs-demo-backend:latest
    command: npm run start-watch
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - PORT=80
    ports:
      - 80:80
    secrets:
      - db-password
    networks:
      - public
      - private
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  frontend:
    image: <your aws account>.dkr.ecr.<your aws region>.amazonaws.com/docker-ecs-demo-frontend:latest
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      - backend

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
