version: "3.7"

services:
  backend:
    image: 752419465350.dkr.ecr.us-east-1.amazonaws.com/docker-ecs-demo-backend:latest
    command: npm run start-watch
    environment:
      - DATABASE_DB=example_rds
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=example-rds.chdqlk4ehvae.us-east-1.rds.amazonaws.com
    ports:
      - 8080:8080
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    networks:
      - public
      - private

  frontend:
    image: 752419465350.dkr.ecr.us-east-1.amazonaws.com/docker-ecs-demo-frontend:latest
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      - backend

networks:
  public:
  private:

secrets:
  db-password:
    file: db/password.txt
