version: "3.7"
services:
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
    command: npm run start-watch
    environment:
      - DATABASE_DB=example-aws
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=example-aws.c9uz4aaw1jzb.ap-southeast-2.rds.amazonaws.com
      - NODE_ENV=development
    ports:
      - 80:80
      - 9229:9229
      - 9230:9230
    secrets:
      - db-password
    networks:
      - public
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      - backend
networks:
  public:
secrets:
  db-password:
    file: db/password.txt
